/** Draft default plan (not wired into app yet). */
export const fastShip = [
  {
    id: "default_koloniezentrum",
    kind: "tech",
    name: "Koloniezentrum",
    startTick: 0,
  },
  {
    id: "tech_mrtlma93_b2f4hb",
    kind: "tech",
    name: "Bergbau",
    startTick: 2,
  },
  {
    id: "tech_mrtlmi4w_kb4efq",
    kind: "tech",
    name: "Metallmine",
    startTick: 6,
  },
  {
    id: "tech_mrtlml7b_d1ugmt",
    kind: "tech",
    name: "Kristallmine",
    startTick: 6,
  },
  {
    id: "tech_mrtln3kn_3dksty",
    kind: "tech",
    name: "Robotik",
    startTick: 8,
  },
  {
    id: "tech_mrtlndnr_o853u4",
    kind: "tech",
    name: "Zweite Metallmine",
    startTick: 8,
  },
  {
    id: "tech_mrtlnmof_kh0kot",
    kind: "tech",
    name: "Zweite Kristallmine",
    startTick: 8,
  },
  {
    id: "tech_mrtlotnr_iprwzu",
    kind: "tech",
    name: "Tiefe Metallminen",
    startTick: 16,
  },
  {
    id: "tech_mrtlp0hz_z98dbu",
    kind: "tech",
    name: "Tiefe Kristallminen",
    startTick: 16,
  },
  {
    id: "tech_mrupldiq_gzl32m",
    kind: "tech",
    name: "Fortgeschrittene Robotik",
    startTick: 24,
  },
  {
    id: "tech_mrupmso1_llr8pa",
    kind: "tech",
    name: "Raumfahrt",
    startTick: 24,
  },
  {
    id: "tech_mrupnkgx_nhtpwz",
    kind: "tech",
    name: "Planetare Werften",
    startTick: 38,
  },
  {
    id: "tech_mrupnplu_p8p690",
    kind: "tech",
    name: "Vollautomatisierte Metallmine",
    startTick: 40,
  },
  {
    id: "tech_mrupns6y_py5ux1",
    kind: "tech",
    name: "Vollautomatisierte Kristallmine",
    startTick: 40,
  },
  {
    id: "tech_mrupo4oy_nzizr3",
    kind: "tech",
    name: "Wiederverwendbare Trägersysteme",
    startTick: 62,
  },
  {
    id: "tech_mrupobex_cd2x36",
    kind: "tech",
    name: "Bergbaulaser",
    startTick: 62,
  },
  {
    id: "tech_mrupos8j_wwn9cq",
    kind: "tech",
    name: "Raumstation",
    startTick: 74,
  },
  {
    id: "tech_mrupoyih_zgpkew",
    kind: "tech",
    name: "Observatorium",
    startTick: 74,
  },
  {
    id: "tech_mruppj9l_088jh1",
    kind: "tech",
    name: "Extraktor",
    startTick: 98,
  },
  {
    id: "tech_mruqaz6j_pe4in1",
    kind: "tech",
    name: "Fabriken für Raumantriebe",
    startTick: 98,
  },
  {
    id: "tech_mruqbebf_z8ybhg",
    kind: "tech",
    name: "Waffenfabriken",
    startTick: 105,
  },
  {
    id: "tech_mruqdr0j_ychpqb",
    kind: "tech",
    name: "Traktorstrahl",
    startTick: 153,
  },
  {
    id: "tech_mruqmmcs_1igb1b",
    kind: "tech",
    name: "Raumwerften",
    startTick: 126,
  },
  {
    id: "tech_mruqs0tx_c64xam",
    kind: "tech",
    name: "Kinetische Raketen",
    startTick: 153,
  },
  {
    id: "tech_mruqs9ks_estbk4",
    kind: "tech",
    name: "Militärischer Ionenantrieb",
    startTick: 154,
  },
  {
    id: "tech_mruqsjus_1o9s2i",
    kind: "tech",
    name: "Kaperschiff",
    startTick: 179,
  },
  {
    id: "tech_mruqt0md_erdee5",
    kind: "tech",
    name: "Longsteen Feld",
    startTick: 221,
  },
  {
    id: "tech_mruqt2w5_gm18k9",
    kind: "tech",
    name: "Schildschiff",
    startTick: 257,
  },
  {
    id: "eco_mruqw5k4_cdhnus",
    kind: "economy",
    startTick: 118,
    asteroids: 10,
    extractors: 91,
    resource: "met",
  },
  {
    id: "tech_mrusauj2_p5lcu0",
    kind: "tech",
    name: "Marineakademie",
    startTick: 185,
  },
  {
    id: "tech_mrusbre6_t75e5b",
    kind: "tech",
    name: "Sektorscan",
    startTick: 185,
  },
  {
    id: "recon_mrusc8hy_1ww70g",
    kind: "recon",
    name: "Scanverstärker",
    startTick: 187,
    count: 10,
  },
  {
    id: "eco_mrusi8l3_h9rdqx",
    kind: "economy",
    startTick: 126,
    asteroids: 0,
    extractors: 7,
    resource: "met",
  },
  {
    id: "eco_mrusl64z_whhcf7",
    kind: "economy",
    startTick: 153,
    asteroids: 0,
    extractors: 43,
    resource: "met",
  },
  {
    id: "unit_mrusnvx7_we2owy",
    kind: "unit",
    name: "Cleptor",
    startTick: 221,
    count: 400,
  },
  {
    id: "eco_mrusq8ur_s83u6e",
    kind: "economy",
    startTick: 179,
    asteroids: 0,
    extractors: 38,
    resource: "met",
  },
  {
    id: "tech_mrutjq7q_pche80",
    kind: "tech",
    name: "Abfangjäger",
    startTick: 257,
  },
  {
    id: "tech_mrutk29a_02cjer",
    kind: "tech",
    name: "Protonenantrieb",
    startTick: 298,
  },
  {
    id: "tech_mrutk71q_zlhl1h",
    kind: "tech",
    name: "Protonentorpedos",
    startTick: 225,
  },
  {
    id: "eco_mrutnkm6_i72vqb",
    kind: "economy",
    startTick: 221,
    asteroids: 0,
    extractors: 10,
    resource: "met",
  },
  {
    id: "eco_mruu6r4f_a8cn05",
    kind: "economy",
    startTick: 257,
    asteroids: 20,
    extractors: 43,
    resource: "met",
  },
];
