type TechTreeType = "building" | "research";

/** Alle Gebäude- und Forschungsnamen aus dem Techtree. */
export type TechName =
  | "Koloniezentrum"
  | "Bergbau"
  | "Kristallmine"
  | "Metallmine"
  | "Zweite Kristallmine"
  | "Zweite Metallmine"
  | "Robotik"
  | "Tiefe Kristallminen"
  | "Tiefe Metallminen"
  | "Fortgeschrittene Robotik"
  | "Bergungstechnologie"
  | "Vollautomatisierte Kristallmine"
  | "Vollautomatisierte Metallmine"
  | "Planetare Werften"
  | "Raumfahrt"
  | "Abfangjäger"
  | "Wiederverwendbare Trägersysteme"
  | "Leichtes Orbitalgeschütz"
  | "Observatorium"
  | "Sektorscan"
  | "Einheitenscan"
  | "Geschützscan"
  | "Militärscan"
  | "Nachrichtenscan"
  | "Aufwertung des Militärscans"
  | "Aufwertung des Nachrichtenscans"
  | "Opto-elektrische Störfelder"
  | "Intergalaktisches Ortungssystem"
  | "Raumstation"
  | "Raumhafen"
  | "Interstellarer Handel"
  | "Handelsplatz"
  | "Bergbaulaser"
  | "Extraktor"
  | "Traktorstrahl"
  | "Kaperschiff"
  | "Longsteen Feld"
  | "Schildschiff"
  | "Raumwerften"
  | "Planetarer Schild"
  | "Fabriken für Raumantriebe"
  | "Militärischer Ionenantrieb"
  | "Protonenantrieb"
  | "Nanofabriken"
  | "Fusionsantrieb"
  | "Mak-tol Werften"
  | "Antimaterieantrieb"
  | "Kristalline KI"
  | "Fregatte"
  | "Zerstörer"
  | "Leichtes Raumgeschütz"
  | "Jäger"
  | "Bomber"
  | "Kreuzer"
  | "Mittleres Raumgeschütz"
  | "Trägerschiff"
  | "Schlachtschiff"
  | "Schweres Raumgeschütz"
  | "Raumbasis"
  | "Kommandoschiff"
  | "Waffenfabriken"
  | "Kinetische Raketen"
  | "Protonentorpedos"
  | "Plasmawerfer"
  | "Plasmabomben"
  | "Fusionstorpedos"
  | "Quantum Rotationskanonen"
  | "Antimaterietorpedos"
  | "Laserphalanx"
  | "Artilleriesysteme"
  | "Protonenlaserartillerie"
  | "Fluxpartikelartillerie"
  | "Positronenlaserartillerie"
  | "Marineakademie"
  | "Akademieanbau: Offensive Kriegsführung"
  | "Akademieanbau: Defensive Kriegsführung"
  | "Hangar"
  | "Reparaturdock"
  | "Casino";

export type TechTreeEntry = {
  name: TechName;
  type: TechTreeType;
  ticks: number;
  time: number;
  cost: {
    met: number;
    kris: number;
  };
  dependencies: TechName[];
  eliminates: TechName[];
};
