/** Draft plan (not wired into the app yet). */
import type { PlanEntry, PlanTemplate } from "@/gn-data/plan";

export const fastExen: PlanTemplate = {
  id: "fast_exen",
  label: "Fast Exen",
  plan: [
    {
      id: "default_koloniezentrum",
      kind: "tech",
      name: "Koloniezentrum",
      startTick: 0,
    },
    {
      id: "tech_mtfqrtj1_zxodxy",
      kind: "tech",
      name: "Bergbau",
      startTick: 2,
    },
    {
      id: "tech_mtfqrx7p_jalatc",
      kind: "tech",
      name: "Metallmine",
      startTick: 6,
    },
    {
      id: "tech_mtfqrynx_4k9zef",
      kind: "tech",
      name: "Kristallmine",
      startTick: 6,
    },
    {
      id: "tech_mtfqs3f1_8vcjzb",
      kind: "tech",
      name: "Robotik",
      startTick: 8,
    },
    {
      id: "tech_mtfqs4va_nuqdys",
      kind: "tech",
      name: "Zweite Kristallmine",
      startTick: 8,
    },
    {
      id: "tech_mtfqs6wu_9lwdpa",
      kind: "tech",
      name: "Zweite Metallmine",
      startTick: 8,
    },
    {
      id: "tech_mtfqttfq_xmz9o2",
      kind: "tech",
      name: "Tiefe Metallminen",
      startTick: 14,
    },
    {
      id: "tech_mtfqtwq6_dy7yks",
      kind: "tech",
      name: "Tiefe Kristallminen",
      startTick: 14,
    },
    {
      id: "tech_mtfqw11p_7ugvb9",
      kind: "tech",
      name: "Raumfahrt",
      startTick: 19,
    },
    {
      id: "tech_mtfqwp0l_o1y59x",
      kind: "tech",
      name: "Fortgeschrittene Robotik",
      startTick: 25,
    },
    {
      id: "tech_mtfqxhel_1tddrs",
      kind: "tech",
      name: "Planetare Werften",
      startTick: 33,
    },
    {
      id: "tech_mtfqxpkd_3qpm06",
      kind: "tech",
      name: "Vollautomatisierte Metallmine",
      startTick: 41,
    },
    {
      id: "tech_mtfqxrj9_w2rad9",
      kind: "tech",
      name: "Vollautomatisierte Kristallmine",
      startTick: 41,
    },
    {
      id: "tech_mtfqxz65_p4q7jf",
      kind: "tech",
      name: "Wiederverwendbare Trägersysteme",
      startTick: 57,
    },
    {
      id: "tech_mtfqyx1i_8xsli4",
      kind: "tech",
      name: "Raumstation",
      startTick: 69,
    },
    {
      id: "tech_mtfqz0r9_44zn14",
      kind: "tech",
      name: "Observatorium",
      startTick: 69,
    },
    {
      id: "tech_mtfqzmwd_fma22x",
      kind: "tech",
      name: "Bergbaulaser",
      startTick: 73,
    },
    {
      id: "tech_mtfr03f1_6t74uo",
      kind: "tech",
      name: "Extraktor",
      startTick: 93,
    },
    {
      id: "eco_mtfr213a_6cv0ly",
      kind: "economy",
      startTick: 113,
      asteroids: 6,
      extractorsMet: 81,
      extractorsKris: 0,
    },
    {
      id: "tech_mtfr3cjq_vcmyy2",
      kind: "tech",
      name: "Fabriken für Raumantriebe",
      startTick: 93,
    },
    {
      id: "recon_mtfr4sha_qpfxrd",
      kind: "recon",
      name: "Scanverstärker",
      startTick: 93,
      count: 1,
    },
    {
      id: "tech_mtfr5h27_53dhll",
      kind: "tech",
      name: "Sektorscan",
      startTick: 94,
    },
    {
      id: "tech_mtfr9qcw_u1yr0b",
      kind: "tech",
      name: "Waffenfabriken",
      startTick: 104,
    },
    {
      id: "tech_mtfrc44x_vq3mtq",
      kind: "tech",
      name: "Raumwerften",
      startTick: 121,
    },
    {
      id: "tech_mtfrecg1_t1mbzp",
      kind: "tech",
      name: "Traktorstrahl",
      startTick: 152,
    },
    {
      id: "tech_mtfreo4p_z51ja3",
      kind: "tech",
      name: "Kaperschiff",
      startTick: 178,
    },
    {
      id: "eco_mtfrfmy9_97l9zk",
      kind: "economy",
      startTick: 121,
      asteroids: 1,
      extractorsMet: 7,
      extractorsKris: 0,
    },
    {
      id: "tech_mtfrfypd_ei6k0i",
      kind: "tech",
      name: "Longsteen Feld",
      startTick: 220,
    },
    {
      id: "tech_mtfrg0kh_fwplxg",
      kind: "tech",
      name: "Schildschiff",
      startTick: 256,
    },
    {
      id: "tech_mtfrgamp_owyb2p",
      kind: "tech",
      name: "Militärischer Ionenantrieb",
      startTick: 149,
    },
    {
      id: "tech_mtfrgdw9_ta6fwm",
      kind: "tech",
      name: "Kinetische Raketen",
      startTick: 152,
    },
    {
      id: "eco_mtfrhfx5_36iykj",
      kind: "economy",
      startTick: 152,
      asteroids: 4,
      extractorsMet: 49,
      extractorsKris: 0,
    },
    {
      id: "eco_mtfril6h_6sa7wf",
      kind: "economy",
      startTick: 178,
      asteroids: 0,
      extractorsMet: 40,
      extractorsKris: 0,
    },
    {
      id: "unit_mtfrj8ll_wkxw2z",
      kind: "unit",
      name: "Cleptor",
      startTick: 220,
      count: 500,
    },
    {
      id: "tech_mtfrlxpd_qs4zne",
      kind: "tech",
      name: "Marineakademie",
      startTick: 216,
    },
    {
      id: "tech_mtfrt71e_g5ue97",
      kind: "tech",
      name: "Abfangjäger",
      startTick: 252,
    },
  ] satisfies PlanEntry[],
};
