/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngriffRouteImport } from './routes/angriff'
import { Route as KampfwerteRouteImport } from './routes/kampfwerte'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ScanIndexRouteImport } from './routes/scan/index'
import { Route as ScanNewsRouteImport } from './routes/scan/news'
import { Route as ScanSektorRouteImport } from './routes/scan/sektor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngriffRoute = AngriffRouteImport.update({
  id: '/angriff',
  path: '/angriff',
  getParentRoute: () => rootRouteImport,
} as any)
const KampfwerteRoute = KampfwerteRouteImport.update({
  id: '/kampfwerte',
  path: '/kampfwerte',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanRoute,
} as any)
const ScanNewsRoute = ScanNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ScanRoute,
} as any)
const ScanSektorRoute = ScanSektorRouteImport.update({
  id: '/sektor',
  path: '/sektor',
  getParentRoute: () => ScanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angriff': typeof AngriffRoute
  '/kampfwerte': typeof KampfwerteRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/news': typeof ScanNewsRoute
  '/scan/sektor': typeof ScanSektorRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angriff': typeof AngriffRoute
  '/kampfwerte': typeof KampfwerteRoute
  '/scan/news': typeof ScanNewsRoute
  '/scan/sektor': typeof ScanSektorRoute
  '/scan': typeof ScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angriff': typeof AngriffRoute
  '/kampfwerte': typeof KampfwerteRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/news': typeof ScanNewsRoute
  '/scan/sektor': typeof ScanSektorRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angriff'
    | '/kampfwerte'
    | '/scan'
    | '/scan/news'
    | '/scan/sektor'
    | '/scan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/angriff' | '/kampfwerte' | '/scan/news' | '/scan/sektor' | '/scan'
  id:
    | '__root__'
    | '/'
    | '/angriff'
    | '/kampfwerte'
    | '/scan'
    | '/scan/news'
    | '/scan/sektor'
    | '/scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngriffRoute: typeof AngriffRoute
  KampfwerteRoute: typeof KampfwerteRoute
  ScanRoute: typeof ScanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angriff': {
      id: '/angriff'
      path: '/angriff'
      fullPath: '/angriff'
      preLoaderRoute: typeof AngriffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampfwerte': {
      id: '/kampfwerte'
      path: '/kampfwerte'
      fullPath: '/kampfwerte'
      preLoaderRoute: typeof KampfwerteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/news': {
      id: '/scan/news'
      path: '/news'
      fullPath: '/scan/news'
      preLoaderRoute: typeof ScanNewsRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/sektor': {
      id: '/scan/sektor'
      path: '/sektor'
      fullPath: '/scan/sektor'
      preLoaderRoute: typeof ScanSektorRouteImport
      parentRoute: typeof ScanRoute
    }
  }
}

interface ScanRouteChildren {
  ScanNewsRoute: typeof ScanNewsRoute
  ScanSektorRoute: typeof ScanSektorRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanNewsRoute: ScanNewsRoute,
  ScanSektorRoute: ScanSektorRoute,
  ScanIndexRoute: ScanIndexRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngriffRoute: AngriffRoute,
  KampfwerteRoute: KampfwerteRoute,
  ScanRoute: ScanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
